// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoLq6Su9uV952fi4K8CVvkvbUiaq7aCsE',
    appId: '1:920225788373:web:3f30fd9173700616ef8d5c',
    messagingSenderId: '920225788373',
    projectId: 'mapa-kaon',
    authDomain: 'mapa-kaon.firebaseapp.com',
    storageBucket: 'mapa-kaon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC84Li6KwTgiHnTNVWtlcqVuZ70qhZ9DKg',
    appId: '1:920225788373:android:b33df0dc5bc983b0ef8d5c',
    messagingSenderId: '920225788373',
    projectId: 'mapa-kaon',
    storageBucket: 'mapa-kaon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkvzhF_n3kga9gRVx3N_9rpS_KR2IyaDw',
    appId: '1:920225788373:ios:dae0651842c7c02eef8d5c',
    messagingSenderId: '920225788373',
    projectId: 'mapa-kaon',
    storageBucket: 'mapa-kaon.firebasestorage.app',
    iosBundleId: 'com.example.mapTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkvzhF_n3kga9gRVx3N_9rpS_KR2IyaDw',
    appId: '1:920225788373:ios:dae0651842c7c02eef8d5c',
    messagingSenderId: '920225788373',
    projectId: 'mapa-kaon',
    storageBucket: 'mapa-kaon.firebasestorage.app',
    iosBundleId: 'com.example.mapTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoLq6Su9uV952fi4K8CVvkvbUiaq7aCsE',
    appId: '1:920225788373:web:1b3454395aca9f7fef8d5c',
    messagingSenderId: '920225788373',
    projectId: 'mapa-kaon',
    authDomain: 'mapa-kaon.firebaseapp.com',
    storageBucket: 'mapa-kaon.firebasestorage.app',
  );
}
